//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquorShop_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int PageId { get; set; }
        public string PageTitle { get; set; }
        public string Slug { get; set; }
        public string Body { get; set; }
        public Nullable<int> Sorting { get; set; }
        public Nullable<bool> HasSidebar { get; set; }
    }
}
